[package]
name = "task-mangement-api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono="0.4.38"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" 
actix-web = "4"
rusqlite="0.32.1"
